version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: ./src/deployment/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
    command: "npm run watch"